FUNC LABEL 0
    MOV STK A VAL 5
    MOV STK B VAL 10
    REF REG 0 PTR A
    CAL VAL 5
    REF REG 0 PTR B
    CAL VAL 5
    REF REG 0 PTR A
    PRINT STK A
    PRINT STK B
    RET
FUNC LABEL 5
    MOV STK A VAL 20
    MOV REG 0 PTR A
    RET
